#!/usr/bin/env node
/**
 * ╔══════════════════════════════════════════════════╗
 * ║  AGENT 2 — PLANNER AGENT                        ║
 * ║  Takes a triaged issue and produces a detailed  ║
 * ║  implementation plan with file-level tasks.     ║
 * ╚══════════════════════════════════════════════════╝
 *
 * Inputs (env):
 *   ISSUE_NUMBER, TRIAGE_RESULT (JSON from triage agent)
 *   GITHUB_TOKEN, ANTHROPIC_API_KEY
 *
 * Outputs: Posts plan as issue comment, writes tasks JSON
 */

import { callClaudeJSON, log } from '../shared/claude.js'
import { github } from '../shared/github.js'

const AGENT = 'planner'

const SYSTEM = `You are the Planner Agent for CosmicSage — a Vedic astrology React/Vite app.

Tech stack:
- Frontend: React 18, Vite, Tailwind CSS, Zustand, Framer Motion
- RTC: Agora RTC SDK (agora-rtc-sdk-ng) — src/services/agora.js
- Payments: Razorpay Checkout — src/services/razorpay.js
- State: Zustand stores in src/store/index.js
- Routing: React Router v6

File structure:
src/
  components/ (Navbar, AstrologerCard, CallModal, WalletModal, AuthModal, StarField)
  pages/ (Home, Astrologers, AstrologerDetail, Wallet, Profile)
  services/ (agora.js, razorpay.js)
  hooks/ (useAgoraCall.js, useRazorpay.js)
  store/ (index.js — auth, wallet, call, astrologer stores)

Produce a JSON implementation plan:
{
  "planTitle": string,
  "overview": string,
  "tasks": [
    {
      "id": "T1",
      "title": string,
      "type": "create" | "modify" | "delete" | "test",
      "file": string (relative path),
      "description": string,
      "acceptanceCriteria": string[],
      "dependencies": string[] (other task IDs),
      "estimatedMinutes": number
    }
  ],
  "testingStrategy": string,
  "risks": string[],
  "totalEstimatedMinutes": number
}`

async function run() {
  const issueNumber = parseInt(process.env.ISSUE_NUMBER)
  const triageRaw = process.env.TRIAGE_RESULT
  if (!issueNumber) throw new Error('ISSUE_NUMBER required')

  log(AGENT, 'info', 'Starting planning', { issueNumber })

  const triage = triageRaw ? JSON.parse(triageRaw) : null
  const issue = await github.getIssue(issueNumber)

  const plan = await callClaudeJSON({
    system: SYSTEM,
    user: `Create an implementation plan for this issue:

Title: ${issue.title}
Body: ${issue.body || '(no description)'}

Triage classification:
${triage ? JSON.stringify(triage, null, 2) : 'Not available'}

Produce a detailed, file-level implementation plan.`,
    maxTokens: 3000,
  })

  log(AGENT, 'info', 'Plan generated', { taskCount: plan.tasks?.length })

  // Format markdown table of tasks
  const taskTable = plan.tasks.map(t =>
    `| ${t.id} | ${t.title} | \`${t.file}\` | ${t.type} | ~${t.estimatedMinutes}m |`
  ).join('\n')

  const comment = `## 📋 CosmicSage Planner Agent

### ${plan.planTitle}

${plan.overview}

#### Implementation Tasks

| ID | Task | File | Type | Est. |
|----|------|------|------|------|
${taskTable}

**Total estimate:** ~${plan.totalEstimatedMinutes} minutes

#### Testing Strategy
${plan.testingStrategy}

${plan.risks.length > 0 ? `#### ⚠️ Risks\n${plan.risks.map(r => `- ${r}`).join('\n')}` : ''}

---
*Generated by the CosmicSage Planner Agent*`

  await github.createIssueComment(issueNumber, comment)
  log(AGENT, 'info', 'Plan posted to issue')

  // Write outputs
  if (process.env.GITHUB_OUTPUT) {
    const fs = await import('fs')
    fs.appendFileSync(process.env.GITHUB_OUTPUT,
      `plan=${JSON.stringify(plan)}\n`
    )
    fs.appendFileSync(process.env.GITHUB_OUTPUT,
      `task_count=${plan.tasks.length}\n`
    )
  }

  // Save plan to file for coder agent
  const fs = await import('fs')
  fs.writeFileSync('/tmp/cosmicsage_plan.json', JSON.stringify(plan, null, 2))
  log(AGENT, 'info', 'Plan saved to /tmp/cosmicsage_plan.json')

  console.log(JSON.stringify(plan, null, 2))
  return plan
}

run().catch(err => {
  log(AGENT, 'error', err.message)
  process.exit(1)
})
